"""Sunshine Table edit Year Col

Revision ID: 214a4c1d372f
Revises: 5b448337afef
Create Date: 2020-11-02 13:29:16.014669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214a4c1d372f'
down_revision = '5b448337afef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sunshine_calendar_year'), 'sunshine', ['calendar_year'], unique=False)
    op.create_index(op.f('ix_sunshine_first_name'), 'sunshine', ['first_name'], unique=False)
    op.create_index(op.f('ix_sunshine_last_name'), 'sunshine', ['last_name'], unique=False)
    op.create_index(op.f('ix_sunshine_salary'), 'sunshine', ['salary'], unique=False)
    op.create_index(op.f('ix_sunshine_sector'), 'sunshine', ['sector'], unique=False)
    op.create_index(op.f('ix_sunshine_taxable'), 'sunshine', ['taxable'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sunshine_taxable'), table_name='sunshine')
    op.drop_index(op.f('ix_sunshine_sector'), table_name='sunshine')
    op.drop_index(op.f('ix_sunshine_salary'), table_name='sunshine')
    op.drop_index(op.f('ix_sunshine_last_name'), table_name='sunshine')
    op.drop_index(op.f('ix_sunshine_first_name'), table_name='sunshine')
    op.drop_index(op.f('ix_sunshine_calendar_year'), table_name='sunshine')
    # ### end Alembic commands ###
